### ISSUE TITLE
Cannot read property '0' of undefined and direction

### ISSUE THREAD

**Issue by arnaubosch** [Mario-Duarte/image-zoom-plugin#1]
Hi! Nice work.

I am getting this error:

Uncaught TypeError: Cannot read property '0' of undefined
    at r (image-zoom.min.js:14)
    at HTMLElement.<anonymous> (image-zoom.min.js:14)
    at HTMLElement.dispatch (jquery-1.12.4.js:5226)
    at HTMLElement.elemData.handle (jquery-1.12.4.js:4878)

Also for example: I have four images in that order:

image_1    image_2     image_3   image_4

If first I try to zoom the image_3 I'm able only to the zoom to the image_3 and image_4.

If first I try to zoom in the image_1 I am ablt to zoom to the image_1, image_2, image_3 and image_4.

It seems that there is a direction. I can't zoom the previous elems of the selected image.

**Comment by Mario-Duarte** [comment]
Thanks for your feedback, I will definitely look into this.

**Comment by Mario-Duarte** [comment]
@arnaubosch if you look at the example page [here](https://mario-duarte.github.io/image-zoom-plugin/), you can see that you can click on the second or third image and the first one still works, can you perhaps share your code so I can further assist you?

**Comment by Mario-Duarte** [comment]
@arnaubosch I have updated the [demo page](https://mario-duarte.github.io/image-zoom-plugin/) to include at the bottom a section with multiple images using the same class with a code example, Hope this helps with your issue.

**Comment by Mario-Duarte** [comment]
Closing this issue due to lack of feedback
