### ISSUE TITLE
Sorry, again a request for choosing a license

### ISSUE THREAD

**Issue by EmKarr** [Mario-Duarte/image-zoom-plugin#13]
Dear Mario,

I am using your image-zoom-plugin in a non-commercial open source project, which will be published by my university. For legal reasons it would be a good idea if your code is published under some kind of license, e.g. MIT or BSD 3-Clause, or just public domain are examples of licensed that would fit our purposes (basically: free for use, modify and circulate at least for non-commercial purposes), or whatever you see fit. But giving no license at all seems to be possibly problematic.

It would be great if you could decide for a license and add a corresponding LICENSE file to your repository.

Best wishes,
and thank you very much for your code and support,
Michael

**Comment by Mario-Duarte** [comment]
Hi Michael, I will look into this and action it. Most Likely I will add a MIT license to it.
