### ISSUE TITLE
This plugin not working on mobile devices

### ISSUE THREAD

**Issue by hamwentrawat** [Mario-Duarte/image-zoom-plugin#15]
This plugin not working on mobile devices with touch event for dragging zoomed image If we want drag image to see

**Comment by Mario-Duarte** [comment]
This should be fixed since [last update](https://github.com/Mario-Duarte/image-zoom-plugin/pull/17)

**Comment by Mario-Duarte** [comment]
You can download the updated [version here](https://github.com/Mario-Duarte/image-zoom-plugin/releases/tag/1.1.0)
