### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tinaflashaim** [Mario-Duarte/image-zoom-plugin#5]
Hi there!
Great work and great plugin! Exactly what I am looking for.
Just want to know the license of this plugin, if it's MIT or can be used commercially?

**Comment by Mario-Duarte** [comment]
Hi @tinaflashaim ,
Glad this fits right in what you were looking for and can help you in your projects!
Do you want to use this in a commercial project? Do you require support? 
Any [donation is very much appreciated](https://paypal.me/MarioDuarte?locale.x=en_GB) and would help me a lot!
Feel free to message me privately over on Twitter @MDesignsuk.

**Comment by Mario-Duarte** [comment]
@tinaflashaim Just opened an account on buymeacoffee you can now support me and my work!<br/>
<a href="https://www.buymeacoffee.com/marioduarte"><img src="https://img.buymeacoffee.com/button-api/?text=Buy me a Coffee&emoji=&slug=marioduarte&button_colour=FF5F5F&font_colour=ffffff&font_family=Lato&outline_colour=000000&coffee_colour=FFDD00"></a>
